//go:build !ignore_autogenerated

/*
Copyright The Plumb Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Adaptive) DeepCopyInto(out *Adaptive) {
	*out = *in
	if in.Burst != nil {
		in, out := &in.Burst, &out.Burst
		*out = new(Burst)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Adaptive.
func (in *Adaptive) DeepCopy() *Adaptive {
	if in == nil {
		return nil
	}
	out := new(Adaptive)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicy) DeepCopyInto(out *AdaptivePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicy.
func (in *AdaptivePolicy) DeepCopy() *AdaptivePolicy {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdaptivePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicyList) DeepCopyInto(out *AdaptivePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdaptivePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicyList.
func (in *AdaptivePolicyList) DeepCopy() *AdaptivePolicyList {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdaptivePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicySpec) DeepCopyInto(out *AdaptivePolicySpec) {
	*out = *in
	out.Workload = in.Workload
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Signals.DeepCopyInto(&out.Signals)
	in.Capacity.DeepCopyInto(&out.Capacity)
	out.Escalation = in.Escalation
	if in.Traffic != nil {
		in, out := &in.Traffic, &out.Traffic
		*out = new(TrafficPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Experimental != nil {
		in, out := &in.Experimental, &out.Experimental
		*out = new(Experimental)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicySpec.
func (in *AdaptivePolicySpec) DeepCopy() *AdaptivePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicyStatus) DeepCopyInto(out *AdaptivePolicyStatus) {
	*out = *in
	if in.Report != nil {
		in, out := &in.Report, &out.Report
		*out = new(ClusterReport)
		(*in).DeepCopyInto(*out)
	}
	if in.Intent != nil {
		in, out := &in.Intent, &out.Intent
		*out = new(Intent)
		(*in).DeepCopyInto(*out)
	}
	if in.Fleet != nil {
		in, out := &in.Fleet, &out.Fleet
		*out = new(FleetStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicyStatus.
func (in *AdaptivePolicyStatus) DeepCopy() *AdaptivePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackendRef) DeepCopyInto(out *BackendRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackendRef.
func (in *BackendRef) DeepCopy() *BackendRef {
	if in == nil {
		return nil
	}
	out := new(BackendRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Burst) DeepCopyInto(out *Burst) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Burst.
func (in *Burst) DeepCopy() *Burst {
	if in == nil {
		return nil
	}
	out := new(Burst)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CapacityPolicy) DeepCopyInto(out *CapacityPolicy) {
	*out = *in
	if in.ReplicaCapacity != nil {
		in, out := &in.ReplicaCapacity, &out.ReplicaCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CapacityPolicy.
func (in *CapacityPolicy) DeepCopy() *CapacityPolicy {
	if in == nil {
		return nil
	}
	out := new(CapacityPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterPlan) DeepCopyInto(out *ClusterPlan) {
	*out = *in
	if in.WaitingSince != nil {
		in, out := &in.WaitingSince, &out.WaitingSince
		*out = (*in).DeepCopy()
	}
	if in.SkippedUntil != nil {
		in, out := &in.SkippedUntil, &out.SkippedUntil
		*out = (*in).DeepCopy()
	}
	if in.GainedAt != nil {
		in, out := &in.GainedAt, &out.GainedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterPlan.
func (in *ClusterPlan) DeepCopy() *ClusterPlan {
	if in == nil {
		return nil
	}
	out := new(ClusterPlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterReport) DeepCopyInto(out *ClusterReport) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.Demand != nil {
		in, out := &in.Demand, &out.Demand
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Saturation != nil {
		in, out := &in.Saturation, &out.Saturation
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Pressure != nil {
		in, out := &in.Pressure, &out.Pressure
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Latency != nil {
		in, out := &in.Latency, &out.Latency
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ErrorRate != nil {
		in, out := &in.ErrorRate, &out.ErrorRate
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ShortSince != nil {
		in, out := &in.ShortSince, &out.ShortSince
		*out = (*in).DeepCopy()
	}
	if in.SafePressure != nil {
		in, out := &in.SafePressure, &out.SafePressure
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.SafeSince != nil {
		in, out := &in.SafeSince, &out.SafeSince
		*out = (*in).DeepCopy()
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]MetricSample, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterReport.
func (in *ClusterReport) DeepCopy() *ClusterReport {
	if in == nil {
		return nil
	}
	out := new(ClusterReport)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterSpec) DeepCopyInto(out *ClusterSpec) {
	*out = *in
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ReplicaCapacity != nil {
		in, out := &in.ReplicaCapacity, &out.ReplicaCapacity
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(BackendRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterSpec.
func (in *ClusterSpec) DeepCopy() *ClusterSpec {
	if in == nil {
		return nil
	}
	out := new(ClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionSummary) DeepCopyInto(out *DecisionSummary) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionSummary.
func (in *DecisionSummary) DeepCopy() *DecisionSummary {
	if in == nil {
		return nil
	}
	out := new(DecisionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EscalationPolicy) DeepCopyInto(out *EscalationPolicy) {
	*out = *in
	out.After = in.After
	out.EarlyAfter = in.EarlyAfter
	out.ReadyTimeout = in.ReadyTimeout
	out.CalmFor = in.CalmFor
	out.Cooldown = in.Cooldown
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EscalationPolicy.
func (in *EscalationPolicy) DeepCopy() *EscalationPolicy {
	if in == nil {
		return nil
	}
	out := new(EscalationPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Experimental) DeepCopyInto(out *Experimental) {
	*out = *in
	if in.Adaptive != nil {
		in, out := &in.Adaptive, &out.Adaptive
		*out = new(Adaptive)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Experimental.
func (in *Experimental) DeepCopy() *Experimental {
	if in == nil {
		return nil
	}
	out := new(Experimental)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FleetStatus) DeepCopyInto(out *FleetStatus) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	in.PhaseSince.DeepCopyInto(&out.PhaseSince)
	if in.LastStep != nil {
		in, out := &in.LastStep, &out.LastStep
		*out = (*in).DeepCopy()
	}
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]ClusterPlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastDecision != nil {
		in, out := &in.LastDecision, &out.LastDecision
		*out = new(DecisionSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.Tracking != nil {
		in, out := &in.Tracking, &out.Tracking
		*out = make([]TrackedDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Recent != nil {
		in, out := &in.Recent, &out.Recent
		*out = make([]RecentDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OutOfSync != nil {
		in, out := &in.OutOfSync, &out.OutOfSync
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FleetStatus.
func (in *FleetStatus) DeepCopy() *FleetStatus {
	if in == nil {
		return nil
	}
	out := new(FleetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Intent) DeepCopyInto(out *Intent) {
	*out = *in
	in.Expires.DeepCopyInto(&out.Expires)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Intent.
func (in *Intent) DeepCopy() *Intent {
	if in == nil {
		return nil
	}
	out := new(Intent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Metric) DeepCopyInto(out *Metric) {
	*out = *in
	if in.Window != nil {
		in, out := &in.Window, &out.Window
		*out = new(v1.Duration)
		**out = **in
	}
	if in.MaxAge != nil {
		in, out := &in.MaxAge, &out.MaxAge
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Metric.
func (in *Metric) DeepCopy() *Metric {
	if in == nil {
		return nil
	}
	out := new(Metric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSample) DeepCopyInto(out *MetricSample) {
	*out = *in
	out.Value = in.Value.DeepCopy()
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSample.
func (in *MetricSample) DeepCopy() *MetricSample {
	if in == nil {
		return nil
	}
	out := new(MetricSample)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecentDecision) DeepCopyInto(out *RecentDecision) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.ReadyAfterSeconds != nil {
		in, out := &in.ReadyAfterSeconds, &out.ReadyAfterSeconds
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecentDecision.
func (in *RecentDecision) DeepCopy() *RecentDecision {
	if in == nil {
		return nil
	}
	out := new(RecentDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteRef) DeepCopyInto(out *RouteRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteRef.
func (in *RouteRef) DeepCopy() *RouteRef {
	if in == nil {
		return nil
	}
	out := new(RouteRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Signals) DeepCopyInto(out *Signals) {
	*out = *in
	if in.SaturationThreshold != nil {
		in, out := &in.SaturationThreshold, &out.SaturationThreshold
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.LatencySLO != nil {
		in, out := &in.LatencySLO, &out.LatencySLO
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.ErrorRateSLO != nil {
		in, out := &in.ErrorRateSLO, &out.ErrorRateSLO
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]Metric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Signals.
func (in *Signals) DeepCopy() *Signals {
	if in == nil {
		return nil
	}
	out := new(Signals)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedDecision) DeepCopyInto(out *TrackedDecision) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
	if in.Floors != nil {
		in, out := &in.Floors, &out.Floors
		*out = make([]TrackedFloor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.FollowedBy != nil {
		in, out := &in.FollowedBy, &out.FollowedBy
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedDecision.
func (in *TrackedDecision) DeepCopy() *TrackedDecision {
	if in == nil {
		return nil
	}
	out := new(TrackedDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrackedFloor) DeepCopyInto(out *TrackedFloor) {
	*out = *in
	if in.ReadyAt != nil {
		in, out := &in.ReadyAt, &out.ReadyAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrackedFloor.
func (in *TrackedFloor) DeepCopy() *TrackedFloor {
	if in == nil {
		return nil
	}
	out := new(TrackedFloor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrafficPolicy) DeepCopyInto(out *TrafficPolicy) {
	*out = *in
	if in.Routes != nil {
		in, out := &in.Routes, &out.Routes
		*out = make([]RouteRef, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrafficPolicy.
func (in *TrafficPolicy) DeepCopy() *TrafficPolicy {
	if in == nil {
		return nil
	}
	out := new(TrafficPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
