//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicy) DeepCopyInto(out *AdaptivePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicy.
func (in *AdaptivePolicy) DeepCopy() *AdaptivePolicy {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdaptivePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicyList) DeepCopyInto(out *AdaptivePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AdaptivePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicyList.
func (in *AdaptivePolicyList) DeepCopy() *AdaptivePolicyList {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AdaptivePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicySpec) DeepCopyInto(out *AdaptivePolicySpec) {
	*out = *in
	out.Workload = in.Workload
	if in.PodRequests != nil {
		in, out := &in.PodRequests, &out.PodRequests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Regions != nil {
		in, out := &in.Regions, &out.Regions
		*out = make([]RegionSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.KnownInstanceTypes != nil {
		in, out := &in.KnownInstanceTypes, &out.KnownInstanceTypes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.Tuning = in.Tuning
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicySpec.
func (in *AdaptivePolicySpec) DeepCopy() *AdaptivePolicySpec {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AdaptivePolicyStatus) DeepCopyInto(out *AdaptivePolicyStatus) {
	*out = *in
	if in.HeartbeatTime != nil {
		in, out := &in.HeartbeatTime, &out.HeartbeatTime
		*out = (*in).DeepCopy()
	}
	if in.LastDecision != nil {
		in, out := &in.LastDecision, &out.LastDecision
		*out = new(DecisionSummary)
		(*in).DeepCopyInto(*out)
	}
	if in.RegionTargets != nil {
		in, out := &in.RegionTargets, &out.RegionTargets
		*out = make([]RegionTarget, len(*in))
		copy(*out, *in)
	}
	if in.LastSafeTargets != nil {
		in, out := &in.LastSafeTargets, &out.LastSafeTargets
		*out = make([]RegionTarget, len(*in))
		copy(*out, *in)
	}
	if in.LastChangeTime != nil {
		in, out := &in.LastChangeTime, &out.LastChangeTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdaptivePolicyStatus.
func (in *AdaptivePolicyStatus) DeepCopy() *AdaptivePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AdaptivePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionSummary) DeepCopyInto(out *DecisionSummary) {
	*out = *in
	in.Time.DeepCopyInto(&out.Time)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionSummary.
func (in *DecisionSummary) DeepCopy() *DecisionSummary {
	if in == nil {
		return nil
	}
	out := new(DecisionSummary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DecisionTuning) DeepCopyInto(out *DecisionTuning) {
	*out = *in
	out.Cooldown = in.Cooldown
	out.ICEWindow = in.ICEWindow
	out.OutcomeHorizon = in.OutcomeHorizon
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DecisionTuning.
func (in *DecisionTuning) DeepCopy() *DecisionTuning {
	if in == nil {
		return nil
	}
	out := new(DecisionTuning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionSpec) DeepCopyInto(out *RegionSpec) {
	*out = *in
	if in.KubeconfigSecretRef != nil {
		in, out := &in.KubeconfigSecretRef, &out.KubeconfigSecretRef
		*out = new(SecretKeyRef)
		**out = **in
	}
	if in.NodePools != nil {
		in, out := &in.NodePools, &out.NodePools
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionSpec.
func (in *RegionSpec) DeepCopy() *RegionSpec {
	if in == nil {
		return nil
	}
	out := new(RegionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RegionTarget) DeepCopyInto(out *RegionTarget) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegionTarget.
func (in *RegionTarget) DeepCopy() *RegionTarget {
	if in == nil {
		return nil
	}
	out := new(RegionTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadRef) DeepCopyInto(out *WorkloadRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadRef.
func (in *WorkloadRef) DeepCopy() *WorkloadRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadRef)
	in.DeepCopyInto(out)
	return out
}
