// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: plumb/decision/v1/decision.proto

package decisionpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DecideRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// question_set names a set defined in decision-service/questions, e.g. "ice_event".
	QuestionSet string `protobuf:"bytes,2,opt,name=question_set,json=questionSet,proto3" json:"question_set,omitempty"`
	// state_json is the compressed summary produced by internal/core/state.
	StateJson string `protobuf:"bytes,3,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	// region_choices are the candidate regions for the target_region question.
	RegionChoices []string `protobuf:"bytes,4,rep,name=region_choices,json=regionChoices,proto3" json:"region_choices,omitempty"`
	// model is the configured instance name to use (e.g. "laya", "jev"); empty = default.
	Model         string `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideRequest) Reset() {
	*x = DecideRequest{}
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideRequest) ProtoMessage() {}

func (x *DecideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideRequest.ProtoReflect.Descriptor instead.
func (*DecideRequest) Descriptor() ([]byte, []int) {
	return file_plumb_decision_v1_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecideRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecideRequest) GetQuestionSet() string {
	if x != nil {
		return x.QuestionSet
	}
	return ""
}

func (x *DecideRequest) GetStateJson() string {
	if x != nil {
		return x.StateJson
	}
	return ""
}

func (x *DecideRequest) GetRegionChoices() []string {
	if x != nil {
		return x.RegionChoices
	}
	return nil
}

func (x *DecideRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

type Answer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	QuestionId string                 `protobuf:"bytes,1,opt,name=question_id,json=questionId,proto3" json:"question_id,omitempty"`
	// type is choice, score or noul.
	Type   string  `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Choice string  `protobuf:"bytes,3,opt,name=choice,proto3" json:"choice,omitempty"`
	Score  float64 `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	// noul is P(true).
	Noul float64 `protobuf:"fixed64,5,opt,name=noul,proto3" json:"noul,omitempty"`
	// confidence is the calibrated confidence after the instance's temperature scaling.
	Confidence    float64            `protobuf:"fixed64,6,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Probabilities map[string]float64 `protobuf:"bytes,7,rep,name=probabilities,proto3" json:"probabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_plumb_decision_v1_decision_proto_rawDescGZIP(), []int{1}
}

func (x *Answer) GetQuestionId() string {
	if x != nil {
		return x.QuestionId
	}
	return ""
}

func (x *Answer) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Answer) GetChoice() string {
	if x != nil {
		return x.Choice
	}
	return ""
}

func (x *Answer) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Answer) GetNoul() float64 {
	if x != nil {
		return x.Noul
	}
	return 0
}

func (x *Answer) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Answer) GetProbabilities() map[string]float64 {
	if x != nil {
		return x.Probabilities
	}
	return nil
}

type DecideResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	RequestId string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// model is the provider's model identifier (e.g. "convaiinnovations/laya", "jev-latest").
	Model     string    `protobuf:"bytes,2,opt,name=model,proto3" json:"model,omitempty"`
	Answers   []*Answer `protobuf:"bytes,3,rep,name=answers,proto3" json:"answers,omitempty"`
	LatencyMs float64   `protobuf:"fixed64,4,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// instance is the configured instance name that answered.
	Instance string `protobuf:"bytes,5,opt,name=instance,proto3" json:"instance,omitempty"`
	// plugin is the plugin type that served the instance (e.g. "laya", "jev").
	Plugin        string `protobuf:"bytes,6,opt,name=plugin,proto3" json:"plugin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecideResponse) Reset() {
	*x = DecideResponse{}
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecideResponse) ProtoMessage() {}

func (x *DecideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecideResponse.ProtoReflect.Descriptor instead.
func (*DecideResponse) Descriptor() ([]byte, []int) {
	return file_plumb_decision_v1_decision_proto_rawDescGZIP(), []int{2}
}

func (x *DecideResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecideResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *DecideResponse) GetAnswers() []*Answer {
	if x != nil {
		return x.Answers
	}
	return nil
}

func (x *DecideResponse) GetLatencyMs() float64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *DecideResponse) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *DecideResponse) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

type ListModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsRequest) Reset() {
	*x = ListModelsRequest{}
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsRequest) ProtoMessage() {}

func (x *ListModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsRequest.ProtoReflect.Descriptor instead.
func (*ListModelsRequest) Descriptor() ([]byte, []int) {
	return file_plumb_decision_v1_decision_proto_rawDescGZIP(), []int{3}
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      string                 `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	Plugin        string                 `protobuf:"bytes,2,opt,name=plugin,proto3" json:"plugin,omitempty"`
	Model         string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	Default       bool                   `protobuf:"varint,5,opt,name=default,proto3" json:"default,omitempty"`
	MaxChoices    int32                  `protobuf:"varint,6,opt,name=max_choices,json=maxChoices,proto3" json:"max_choices,omitempty"`
	MaxStateBytes int32                  `protobuf:"varint,7,opt,name=max_state_bytes,json=maxStateBytes,proto3" json:"max_state_bytes,omitempty"`
	// remote is true when the plugin sends state outside the cluster.
	Remote        bool `protobuf:"varint,8,opt,name=remote,proto3" json:"remote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_plumb_decision_v1_decision_proto_rawDescGZIP(), []int{4}
}

func (x *ModelInfo) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *ModelInfo) GetPlugin() string {
	if x != nil {
		return x.Plugin
	}
	return ""
}

func (x *ModelInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ModelInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ModelInfo) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

func (x *ModelInfo) GetMaxChoices() int32 {
	if x != nil {
		return x.MaxChoices
	}
	return 0
}

func (x *ModelInfo) GetMaxStateBytes() int32 {
	if x != nil {
		return x.MaxStateBytes
	}
	return 0
}

func (x *ModelInfo) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

type ListModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*ModelInfo           `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListModelsResponse) Reset() {
	*x = ListModelsResponse{}
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListModelsResponse) ProtoMessage() {}

func (x *ListModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plumb_decision_v1_decision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListModelsResponse.ProtoReflect.Descriptor instead.
func (*ListModelsResponse) Descriptor() ([]byte, []int) {
	return file_plumb_decision_v1_decision_proto_rawDescGZIP(), []int{5}
}

func (x *ListModelsResponse) GetModels() []*ModelInfo {
	if x != nil {
		return x.Models
	}
	return nil
}

var File_plumb_decision_v1_decision_proto protoreflect.FileDescriptor

const file_plumb_decision_v1_decision_proto_rawDesc = "" +
	"\n" +
	" plumb/decision/v1/decision.proto\x12\x11plumb.decision.v1\"\xad\x01\n" +
	"\rDecideRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12!\n" +
	"\fquestion_set\x18\x02 \x01(\tR\vquestionSet\x12\x1d\n" +
	"\n" +
	"state_json\x18\x03 \x01(\tR\tstateJson\x12%\n" +
	"\x0eregion_choices\x18\x04 \x03(\tR\rregionChoices\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\"\xb5\x02\n" +
	"\x06Answer\x12\x1f\n" +
	"\vquestion_id\x18\x01 \x01(\tR\n" +
	"questionId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06choice\x18\x03 \x01(\tR\x06choice\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x12\n" +
	"\x04noul\x18\x05 \x01(\x01R\x04noul\x12\x1e\n" +
	"\n" +
	"confidence\x18\x06 \x01(\x01R\n" +
	"confidence\x12R\n" +
	"\rprobabilities\x18\a \x03(\v2,.plumb.decision.v1.Answer.ProbabilitiesEntryR\rprobabilities\x1a@\n" +
	"\x12ProbabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"\xcd\x01\n" +
	"\x0eDecideResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05model\x18\x02 \x01(\tR\x05model\x123\n" +
	"\aanswers\x18\x03 \x03(\v2\x19.plumb.decision.v1.AnswerR\aanswers\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x04 \x01(\x01R\tlatencyMs\x12\x1a\n" +
	"\binstance\x18\x05 \x01(\tR\binstance\x12\x16\n" +
	"\x06plugin\x18\x06 \x01(\tR\x06plugin\"\x13\n" +
	"\x11ListModelsRequest\"\xe6\x01\n" +
	"\tModelInfo\x12\x1a\n" +
	"\binstance\x18\x01 \x01(\tR\binstance\x12\x16\n" +
	"\x06plugin\x18\x02 \x01(\tR\x06plugin\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x18\n" +
	"\adefault\x18\x05 \x01(\bR\adefault\x12\x1f\n" +
	"\vmax_choices\x18\x06 \x01(\x05R\n" +
	"maxChoices\x12&\n" +
	"\x0fmax_state_bytes\x18\a \x01(\x05R\rmaxStateBytes\x12\x16\n" +
	"\x06remote\x18\b \x01(\bR\x06remote\"J\n" +
	"\x12ListModelsResponse\x124\n" +
	"\x06models\x18\x01 \x03(\v2\x1c.plumb.decision.v1.ModelInfoR\x06models2\xbb\x01\n" +
	"\x0fDecisionService\x12M\n" +
	"\x06Decide\x12 .plumb.decision.v1.DecideRequest\x1a!.plumb.decision.v1.DecideResponse\x12Y\n" +
	"\n" +
	"ListModels\x12$.plumb.decision.v1.ListModelsRequest\x1a%.plumb.decision.v1.ListModelsResponseB[ZYgithub.com/bluayer/agent-inference-scheduler/internal/core/decision/decisionpb;decisionpbb\x06proto3"

var (
	file_plumb_decision_v1_decision_proto_rawDescOnce sync.Once
	file_plumb_decision_v1_decision_proto_rawDescData []byte
)

func file_plumb_decision_v1_decision_proto_rawDescGZIP() []byte {
	file_plumb_decision_v1_decision_proto_rawDescOnce.Do(func() {
		file_plumb_decision_v1_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plumb_decision_v1_decision_proto_rawDesc), len(file_plumb_decision_v1_decision_proto_rawDesc)))
	})
	return file_plumb_decision_v1_decision_proto_rawDescData
}

var file_plumb_decision_v1_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plumb_decision_v1_decision_proto_goTypes = []any{
	(*DecideRequest)(nil),      // 0: plumb.decision.v1.DecideRequest
	(*Answer)(nil),             // 1: plumb.decision.v1.Answer
	(*DecideResponse)(nil),     // 2: plumb.decision.v1.DecideResponse
	(*ListModelsRequest)(nil),  // 3: plumb.decision.v1.ListModelsRequest
	(*ModelInfo)(nil),          // 4: plumb.decision.v1.ModelInfo
	(*ListModelsResponse)(nil), // 5: plumb.decision.v1.ListModelsResponse
	nil,                        // 6: plumb.decision.v1.Answer.ProbabilitiesEntry
}
var file_plumb_decision_v1_decision_proto_depIdxs = []int32{
	6, // 0: plumb.decision.v1.Answer.probabilities:type_name -> plumb.decision.v1.Answer.ProbabilitiesEntry
	1, // 1: plumb.decision.v1.DecideResponse.answers:type_name -> plumb.decision.v1.Answer
	4, // 2: plumb.decision.v1.ListModelsResponse.models:type_name -> plumb.decision.v1.ModelInfo
	0, // 3: plumb.decision.v1.DecisionService.Decide:input_type -> plumb.decision.v1.DecideRequest
	3, // 4: plumb.decision.v1.DecisionService.ListModels:input_type -> plumb.decision.v1.ListModelsRequest
	2, // 5: plumb.decision.v1.DecisionService.Decide:output_type -> plumb.decision.v1.DecideResponse
	5, // 6: plumb.decision.v1.DecisionService.ListModels:output_type -> plumb.decision.v1.ListModelsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_plumb_decision_v1_decision_proto_init() }
func file_plumb_decision_v1_decision_proto_init() {
	if File_plumb_decision_v1_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plumb_decision_v1_decision_proto_rawDesc), len(file_plumb_decision_v1_decision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plumb_decision_v1_decision_proto_goTypes,
		DependencyIndexes: file_plumb_decision_v1_decision_proto_depIdxs,
		MessageInfos:      file_plumb_decision_v1_decision_proto_msgTypes,
	}.Build()
	File_plumb_decision_v1_decision_proto = out.File
	file_plumb_decision_v1_decision_proto_goTypes = nil
	file_plumb_decision_v1_decision_proto_depIdxs = nil
}
