# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from plumb_decision import decision_pb2 as plumb__decision_dot_decision__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plumb_decision/decision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DecisionServiceStub:
    """DecisionService fronts one or more decision model plugins (Laya, Jev, ...). It is
    called asynchronously by the agent and never on a scaling hot path.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Decide = channel.unary_unary(
                '/plumb.decision.v1.DecisionService/Decide',
                request_serializer=plumb__decision_dot_decision__pb2.DecideRequest.SerializeToString,
                response_deserializer=plumb__decision_dot_decision__pb2.DecideResponse.FromString,
                _registered_method=True)


class DecisionServiceServicer:
    """DecisionService fronts one or more decision model plugins (Laya, Jev, ...). It is
    called asynchronously by the agent and never on a scaling hot path.
    """

    def Decide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Decide': grpc.unary_unary_rpc_method_handler(
                    servicer.Decide,
                    request_deserializer=plumb__decision_dot_decision__pb2.DecideRequest.FromString,
                    response_serializer=plumb__decision_dot_decision__pb2.DecideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'plumb.decision.v1.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('plumb.decision.v1.DecisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DecisionService:
    """DecisionService fronts one or more decision model plugins (Laya, Jev, ...). It is
    called asynchronously by the agent and never on a scaling hot path.
    """

    @staticmethod
    def Decide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/plumb.decision.v1.DecisionService/Decide',
            plumb__decision_dot_decision__pb2.DecideRequest.SerializeToString,
            plumb__decision_dot_decision__pb2.DecideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
