# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: plumb_decision/decision.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'plumb_decision/decision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dplumb_decision/decision.proto\x12\x11plumb.decision.v1\"t\n\rDecideRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0cquestion_set\x18\x02 \x01(\t\x12\x12\n\nstate_json\x18\x03 \x01(\t\x12\x16\n\x0eregion_choices\x18\x04 \x03(\t\x12\r\n\x05model\x18\x05 \x01(\t\"\xe7\x01\n\x06\x41nswer\x12\x13\n\x0bquestion_id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06\x63hoice\x18\x03 \x01(\t\x12\r\n\x05score\x18\x04 \x01(\x01\x12\x0c\n\x04noul\x18\x05 \x01(\x01\x12\x12\n\nconfidence\x18\x06 \x01(\x01\x12\x43\n\rprobabilities\x18\x07 \x03(\x0b\x32,.plumb.decision.v1.Answer.ProbabilitiesEntry\x1a\x34\n\x12ProbabilitiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x95\x01\n\x0e\x44\x65\x63ideResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12*\n\x07\x61nswers\x18\x03 \x03(\x0b\x32\x19.plumb.decision.v1.Answer\x12\x12\n\nlatency_ms\x18\x04 \x01(\x01\x12\x10\n\x08instance\x18\x05 \x01(\t\x12\x0e\n\x06plugin\x18\x06 \x01(\t2`\n\x0f\x44\x65\x63isionService\x12M\n\x06\x44\x65\x63ide\x12 .plumb.decision.v1.DecideRequest\x1a!.plumb.decision.v1.DecideResponseBRZPgithub.com/bluayer/agent-inference-scheduler/internal/core/decisionpb;decisionpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plumb_decision.decision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZPgithub.com/bluayer/agent-inference-scheduler/internal/core/decisionpb;decisionpb'
  _globals['_ANSWER_PROBABILITIESENTRY']._loaded_options = None
  _globals['_ANSWER_PROBABILITIESENTRY']._serialized_options = b'8\001'
  _globals['_DECIDEREQUEST']._serialized_start=52
  _globals['_DECIDEREQUEST']._serialized_end=168
  _globals['_ANSWER']._serialized_start=171
  _globals['_ANSWER']._serialized_end=402
  _globals['_ANSWER_PROBABILITIESENTRY']._serialized_start=350
  _globals['_ANSWER_PROBABILITIESENTRY']._serialized_end=402
  _globals['_DECIDERESPONSE']._serialized_start=405
  _globals['_DECIDERESPONSE']._serialized_end=554
  _globals['_DECISIONSERVICE']._serialized_start=556
  _globals['_DECISIONSERVICE']._serialized_end=652
# @@protoc_insertion_point(module_scope)
